version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - echo install step...
      - pyenv install --skip-existing 3.8.3
      - pyenv global 3.8.3
      - pyenv virtualenv -p python3.8 3.8.3 venv
      - npm install
      - npm install -g serverless
      - serverless --version
  build:
    commands:
      - serverless deploy -v --stage=dev
  post_build:
    commands:
      - echo Finished