version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - echo install step...
      - SLS_DEBUG=*
      - pyenv install --skip-existing 3.8.3
      - pyenv global 3.8.3
      - pyenv virtualenv -p python3.8 3.8.3 venv
      - npm install
      - npm install -g serverless
      - serverless --version
      - pip3 install pytest
  build:
    commands:
      - python -m pytest --junitxml=tests/report.xml
      - serverless deploy -v --stage=dev
  post_build:
    commands:
      - echo Finished
  reports:
    pytest_reports:
      files:
        - report.xml
      base-directory: tests
      file-format: JUNITXML