version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - echo install step...
      # - set SLS_DEBUG=1
      - pyenv install --skip-existing 3.8.6
      - pyenv global 3.8.5
      - pyenv virtualenv -p python3.8 3.8.6 venv
      - npm install
      - npm install -g serverless
      - serverless --version
  build:
    commands:
      - serverless deploy -v --stage=dev
  post_build:
    commands:
      - echo Finished