# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: books
configValidationMode: error

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

custom:
  stage: ${opt:stage, 'dev'}
  dbConnection: ${ssm:/aws/reference/secretsmanager/books/dev/db~true}
  topicName: books-${self:custom.stage}
  topicArn:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - sns
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - ${self:custom.topicName}
  downloadQueueName: books-download-${self:custom.stage}
  
provider:
  name: aws
  runtime: python3.8

  stage: ${self:custom.stage}
  region: ${opt:region, 'eu-central-1'}

  stackTags:
    project: kindle-books-sender

  apiGateway:
    shouldStartNameWithService: true

  apiKeys:
    - name: test1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        !Ref booksTopic

package:
 exclude:
   - tests
   - appConfig.local.json

functions:
  add_book:
    handler: handler.handle_add_book
    events:
     - http:
         path: books
         method: post
         private: true
    environment:
      DB_HOST: ${self:custom.dbConnection.host}
      DB_NAME: ${self:custom.dbConnection.dbname}
      DB_USER: ${self:custom.dbConnection.username}
      DB_PASSWORD: ${self:custom.dbConnection.password}
      DB_ENGINE: postgres
      BOOKS_TOPIC: ${self:custom.topicArn}
  download_book:
    handler: handle_download_book
    events:
      - sqs: 
          arn: 
            !GetAtt downloadQueue.Arn

resources:
  Resources:
    downloadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: books-downloads
    booksTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.topicName}
    downloadDeadletterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.downloadQueueName}-deadletter
        VisibilityTimeout: 300
    downloadQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.downloadQueueName}
        VisibilityTimeout: 300
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - downloadDeadletterQueue
              - Arn
          maxReceiveCount: 3
    downloadSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: 
          Fn::GetAtt: 
            - downloadQueue
            - Arn
        TopicArn: !Ref booksTopic

plugins:
  - serverless-python-requirements

